name: CrackedBlocks
main: lee.code.crackedblocks.CrackedBlocks
version: ${project.version}
api-version: 1.13
authors:
  - Lee
  - Robotv2
commands:
  cb:
    description: Main command for plugin.
    permission: cb.command.use